### ISSUE TITLE
whens release?

### ISSUE THREAD

**Issue by razorman8669** [rollbar/rollbar-react-native#1]
Hi,  curious when you'll be releasing the alpha version to npm?

**Comment by nhducit** [comment]
me too, I cannot install via npm/yarn
```
npm ERR! 404 Not Found: rollbar-react-native@latest

```

**Comment by jessewgibbs** [comment]
Hi there,

We are still working on support for multi-section source maps in our web app.  Once that's ready, we'll release an alpha.  At this point, we're probably looking at a couple of weeks...

**Comment by caphun** [comment]
i seriously need a stable enough version of this. any way the development could be sped up?
