### ISSUE TITLE
Migration from 0.6.1 to 0.7.0 breaks debugger

### ISSUE THREAD

**Issue by OzzieOrca** [rollbar/rollbar-react-native#101]
Migrating to `0.7.0` crashes the app when trying to use the Chrome debugger.

Running `react-native` `0.61.2`.

I get the following error:
```
Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome.
```

![Simulator Screen Shot - iPhone 11 - 2019-11-12 at 13 36 28](https://user-images.githubusercontent.com/756501/68713261-4c131e80-0552-11ea-8a5d-c0eef3d1e0ec.png)

Here's my rollbar config:
```js
import { Client, Configuration } from 'rollbar-react-native';
import Config from 'react-native-config';
import { Platform } from 'react-native';
import DeviceInfo from 'react-native-device-info';

const codeVersion = `${Config.TRAVIS_COMMIT || 'development'}.${Platform.OS}`;

const config = new Configuration(Config.ROLLBAR_ACCESS_TOKEN, {
  enabled: !__DEV__,
  payload: {
    appVersion: DeviceInfo.getBuildNumber(),
    codeBundleId: codeVersion,
    client: {
      javascript: {
        source_map_enabled: true,
        guess_uncaught_frames: true,
        code_version: codeVersion,
      },
    },
  },
});

export const rollbar = new Client(config);
```

**Comment by waltjones** [comment]
@OzzieOrca Thank you for the report. Didn't see this here, but will investigate.

Can you try setting `captureDeviceInfo` to false in your config and see if it will bypass this problem?

**Comment by OzzieOrca** [comment]
Yup this works:
```diff
import { Client, Configuration } from 'rollbar-react-native';
import Config from 'react-native-config';
import { Platform } from 'react-native';
import DeviceInfo from 'react-native-device-info';

const codeVersion = `${Config.TRAVIS_COMMIT || 'development'}.${Platform.OS}`;

const config = new Configuration(Config.ROLLBAR_ACCESS_TOKEN, {
  enabled: !__DEV__,
+ captureDeviceInfo: false,
  payload: {
    appVersion: DeviceInfo.getBuildNumber(),
    codeBundleId: codeVersion,
    client: {
      javascript: {
        source_map_enabled: true,
        guess_uncaught_frames: true,
        code_version: codeVersion,
      },
    },
  },
});

export const rollbar = new Client(config);
```

Thanks for the quick reply! Do you have any docs on what info it collects? I may just stay at the old version if there's something useful in there.

**Comment by OzzieOrca** [comment]
Here's the Android error that seems more specific:
When debugging:

```
TypeError: NativeClient.deviceAttributes is not a function
```
![Screenshot_1573595881](https://user-images.githubusercontent.com/756501/68714326-87aee800-0554-11ea-877a-d95725149bbc.png)

When not debugging:
```
TypeError: undefined is not a function, js engine: hermes
```
![Screenshot_1573595968](https://user-images.githubusercontent.com/756501/68714434-bd53d100-0554-11ea-828e-708b4c352640.png)

**Comment by waltjones** [comment]
To clarify, those errors are without setting `captureDeviceInfo: false`, correct?

**Comment by OzzieOrca** [comment]
Correct. Yes `captureDeviceInfo: false` fixes everything I've mentioned.

**Comment by OzzieOrca** [comment]
I was looking at the diff between 0.6.1 and 0.7.0 https://github.com/rollbar/rollbar-react-native/compare/f98a982df0d0a8cb6461726b16ecbb80d2f714a1...cf3ae7af49f42322d04d967ffe4e184ec4d7d9fe Is the `captureDeviceInfo` stuff a new feature? Sorta looks like it. If disabling it doesn't omit any data I used to have that might be nicer than downgrading.

**Comment by waltjones** [comment]
Great, that's what I expected. Just making sure.

This feature is new to 0.7.0, so an earlier version won't have the extra metadata. The feature adds device information to payloads that are sent from the Javascript side. The metadata is retrieved synchronously (which is what causes the Chrome debugger issue) in order to include it in the initial config of rollbar.js, and still ensure rollbar.js inits before other application code runs.

Ideally you'd disable while debugging and still be able to enable in production.

Example data in the payload:

iOS
```
    "os": {
      "system_name": "iOS", 
      "device_code": "x86_64", 
      "app_name": "reactNativeApp", 
      "code_version": "1", 
      "bundle_identifier": "org.reactjs.native.example.reactNativeApp", 
      "short_version": "1.0", 
      "device_name": "iPhone 8", 
      "os_version": "13.2", 
      "os": "ios"
    }
```
Android:
```
    "os": {
      "phone_model": "Android SDK built for x86", 
      "product": "sdk_gphone_x86", 
      "brand": "google", 
      "android_version": "9", 
      "board": "goldfish_x86", 
      "device": "generic_x86", 
      "os": "android", 
      "manufacturer": "Google"
    }
```

**Comment by OzzieOrca** [comment]
Ok cool. Thanks for your help and quick responses! Hopefully the defaults can get better :)

Here's what I'm going with for now:
```js
import { Client, Configuration } from 'rollbar-react-native';
import Config from 'react-native-config';
import { Platform } from 'react-native';
import DeviceInfo from 'react-native-device-info';

const codeVersion = `${Config.TRAVIS_COMMIT || 'development'}.${Platform.OS}`;

const config = new Configuration(Config.ROLLBAR_ACCESS_TOKEN, {
  enabled: !__DEV__,
  captureDeviceInfo: !__DEV__, // New feature in rollbar-react-native 0.7.0 that breaks Chrome debugging https://github.com/rollbar/rollbar-react-native/issues/101. Disabling in dev.
  payload: {
    appVersion: DeviceInfo.getBuildNumber(),
    codeBundleId: codeVersion,
    client: {
      javascript: {
        source_map_enabled: true,
        guess_uncaught_frames: true,
        code_version: codeVersion,
      },
    },
  },
});

export const rollbar = new Client(config);
```

**Comment by waltjones** [comment]
Looks good. 0.7.1 will have this off by default, and that will be released shortly.

**Comment by ramandika** [comment]
Hey @waltjones, I face the same issue in 0.7.1 . What weird is that at the beginning of the development everything is fine. I can even get error in rollbar dashboard with device info while performing in debugging mode, but later the error arises (have been trying to reinstall my whole project but still get the same error). But the error only arises in my pc, while in my laptop everything still works perfectly. Any suggestion on this?
