### ISSUE TITLE
Implicit instantiation of undefined template 'llvm::Optional<char>'

### ISSUE THREAD

**Issue by MateuszPrasal** [rollbar/rollbar-react-native#102]
Hello ! 
I receive many errors like `Implicit instantiation of undefined template 'llvm::Optional<char>'` in file `Demangle.cpp` during build iOS app. I've tried to update rollbar-react-native to latest version but without any effects. 
I am using:
RN 0.59.9
Rollbar React Native 0.7.0
Xcode 11.2.1

I've tried to find solution in Google, but nowhere is described anything about this. 
I would be really grateful for any help :)

**Comment by waltjones** [comment]
@MateuszPrasal This looks like it is coming from the KSCrash dependency in rollbar-ios. Specifically it looks like it's coming from here:
https://github.com/kstenerud/KSCrash/blob/c9f68ef836804cb774f800cffb97a58811a0c3cd/Source/KSCrash/swift/Basic/Demangle.cpp#L233

I haven't seen this when building for iOS, including on XCode 11.2.1. I'm expecting it to be a conflict of some kind between dependencies, but the KSCrash team (https://github.com/kstenerud/KSCrash/issues) might have the most insight and/or have the most useful follow up questions for you.

**Comment by waltjones** [comment]
I think this is the specific issue: https://github.com/kstenerud/KSCrash/issues/352

**Comment by Janglinator** [comment]
Were you able to find a solution?  Having the same issue.

**Comment by davidesigner** [comment]
The issue seems to be fixed by @waltjones in https://github.com/rollbar/rollbar-ios/pull/275 but the fix is not applied in `rollbar-react-native`...

Is it plan to update the `rollbar-react-native` package soon?

**Comment by waltjones** [comment]
Yes.

**Comment by waltjones** [comment]
Fix released in v0.8.0. https://github.com/rollbar/rollbar-react-native/releases/tag/v0.8.0
