### ISSUE TITLE
Native crashes not working

### ISSUE THREAD

**Issue by daxfrost** [rollbar/rollbar-react-native#112]
I followed the instructions setting up my React Native JS code & actual native layer:

JS / TypeScript layer is reporting both logs & errors correctly, and I can see the updates in Rollbar.

However, on forcing a native crash I don't see a log, I understand crashes are uploaded on next app execution, so I created the following crash that only happens once after install on Android (1/0):

![image](https://user-images.githubusercontent.com/1788177/80723115-35e02700-8ace-11ea-923b-f7f9180cf785.png)

Config in React Native JS layer:

![image](https://user-images.githubusercontent.com/1788177/80722991-04fff200-8ace-11ea-985b-af26aa10bda6.png)

Setup in Android native layer:

![image](https://user-images.githubusercontent.com/1788177/80723297-7475e180-8ace-11ea-8bc0-f1167d6ee1c4.png)

Is there something I'm missing?

**Comment by waltjones** [comment]
Will be fixed for the next release by https://github.com/rollbar/rollbar-react-native/pull/111, which pulls in https://github.com/rollbar/rollbar-java/pull/200 from rollbar-android.

**Comment by waltjones** [comment]
Fix released in v0.8.0. https://github.com/rollbar/rollbar-react-native/releases/tag/v0.8.0

**Comment by daxfrost** [comment]
Thank you!!
