### ISSUE TITLE
iOS build error v0.8.0 - 'Rollbar.h' file not found

### ISSUE THREAD

**Issue by davidesigner** [rollbar/rollbar-react-native#118]
Hi @waltjones 

Thanks for your last release!

I have the following error on build:
```
▸ Compiling RollbarReactNative.m

❌  /node_modules/rollbar-react-native/ios/RollbarReactNative.h:9:9: 'Rollbar.h' file not found

#import "Rollbar.h"
        ^~~~~~~~~~~
```

Do you know why?

Thanks for your help!

**Comment by waltjones** [comment]
Hi @davidesigner, it looks like the file is missing from Cocoapods because of https://github.com/rollbar/rollbar-ios/pull/283.

We'll get the above fix out asap.

**Comment by davidesigner** [comment]
Thank you very much!

**Comment by waltjones** [comment]
@davidesigner v0.8.1 is out. Let me know if you have any issues with it.

**Comment by davidesigner** [comment]
All is working now 🎉 Thank you 🙏
