### ISSUE TITLE
Source maps not loading stack trace correctly

### ISSUE THREAD

**Issue by dk03** [rollbar/rollbar-react-native#123]
When an error is displayed in the dashboard the stack trace is not displaying the original files as expected, it is displaying the minified files.

This is the process I have followed:

* My react-native code: 
```const rollbar =
  new Client(new Configuration(‘${token}’,
    {
      payload: {
        client: {
          JavaScript: {
            code_version: '2.android',
            environment: ‘production’,
            source_map_enabled: true,
          },
        },
      },
    }));

```

* Build android 

`cd ./android && ./gradlew buildRelease`

* Build source map
`
react-native bundle --platform android --dev false --entry-file index.js --bundle-output 
index.android.bundle --assets-dest android/app/src/main/res/ --sourcemap-output sourcemap.android.js.map --sourcemap-sources-root ./
`
* Curl request:

curl https://api.rollbar.com/api/1/sourcemap \
    -F access_token=‘${token}’ \
    -F version=2.android \
    -F minified_url=http://reactnativehost/index.android.bundle \
    -F source_map=@sourcemap.android.js.map \
    -F index.js=@index.js \
    -F App.js=@App.js

(Potentially separate issue) curl is responding with:

`curl: (52) Empty reply from server`

So I upload it through the console with the same values (selecting the source map outputted in the root directory ./sourcemap.android.js.map).
- minified url: http://reactnativehost/index.android.bundle 
- sourcemap: root/sourcemap.android.js.map         
- version: 2.android

This is the resulting output: 

![image](https://user-images.githubusercontent.com/39081819/82451545-09ed0b80-9aa6-11ea-9695-1f13ed5194c4.png)

* Project structure:

    ├── android                   
    ├── ios                  
    ├── src                    
    ├── sourcemap.android.js.map                
    ├── index.android.bundle                   
    ├── package.json             

* package.json

`dependencies: {
     ...,
    "rollbar-react-native": "^0.8.1"
}`

**Comment by waltjones** [comment]
@dk03 Your curl looks superficially correct, assuming @sourcemap.android.js.map is the correct local path to the map file.

If you will email support@rollbar.com with a link to an example occurrence and this Github Issue, it will be possible to look more specifically at your issue. The majority of the source mapping logic is on the Rollbar back end, and this will help ensure the relevant people will be able to look at this.

**Comment by waltjones** [comment]
@dk03 Is the `curl: (52) Empty reply from server` issue persistent?

**Comment by dk03** [comment]
I've already opened a ticket so will sit tight. 

Yes the curl issue is persistent, happens everytime I try.

**Comment by dk03** [comment]
So it seems the solution to the source map issue was incorrectly configuring the rollbars client interface. 

Changing to this worked:

`"payload": {
  "environment": "production", 
  "client": {
    "javascript": {
      "source_map_enabled": true, 
      "code_version": "1.android"
    }
  }
}`

Notice the two differences are moving the environment out of the client object and correctly lowercasing 'javascript'.

**Comment by dk03** [comment]
Weirdly I am still receiving this from the curl response

> curl: (52) Empty reply from server

**Comment by waltjones** [comment]
@dk03 I forwarded your curl error to the API team, but don't have anything to report back about it.

**Comment by dk03** [comment]
Right the problem was generating the sourcemap as sourcemap.android.js.map - when I change it to sourcemap.android.map it works very well!
