### ISSUE TITLE
Sourcemaps not showing a proper stacktrace

### ISSUE THREAD

**Issue by mtieltjes** [rollbar/rollbar-react-native#128]
We've been using Rollbar successfully for a while now, but never with proper stacktraces.

So when looking at the sourcemaps and documentation, I think I've integrated everything as it should. Yet I cannot get the stacktraces to actually show the correct files.

## Setup
Notes:
- In the following scripts, codeVersion will be the same (commit hash), but for sanity I also checked it with an equal hardcoded version number.
- Below upload script re-generates the bundle. Its only here for completeness, I tried both re-generating the bundle and using the sourcemap a gradle build outputs.
- I have no `android.index.js` or `ios.index.js`, I have 1 entry file `index.js`, I see some also provide an `App.js`, which I do have in the project tree. I'm assuming this should not be the issue (see upload script).
- I do not get any errors at any point whatsover. Everything seems to check out.
- `minified_url` matches what the (unmapped) stacktrace provides
- Rollbar API accepts my uploads with result:
```
{
  "err": 0,
  "result": "{version here}.android"
}
```

Upload script
```bash 
#!/bin/sh
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/index.android.bundle --sourcemap-output sourcemap.android.map --sourcemap-sources-root ./

curl https://api.rollbar.com/api/1/sourcemap \
  -F access_token=$ROLLBAR_ACCESS_TOKEN \
  -F version=$CODE_VERSION.android \
  -F minified_url=http://reactnativehost/index.android.bundle \
  -F source_map=@sourcemap.android.map \
  -F index.js=@index.js
```

```js
const Rollbar = new Client(
  new Configuration(Config.rollbar.accessToken, {
    captureUnhandledRejections: true,
    autoInstrument: false,
    appVersion: version,
    enabled: Constants.rollbar.enabled,
    verbose: true,
    payload: {
      environment: 'production',
      client: {
        javascript: {
          source_map_enabled: true,
          codeVersion: `${codeVersion}.android`,
        },
      },
    },
    captureDeviceInfo: !__DEV__,
  }),
);
```

Result stacktrace
```
File http://reactnativehost/[native code]
line (unknown) in value
File http://reactnativehost/index.android.bundle
line 32 col 720 in value
File http://reactnativehost/index.android.bundle
line 32 col 2611 in value
File http://reactnativehost/index.android.bundle
line 32 col 748 in [anonymous]
File http://reactnativehost/index.android.bundle
line 32 col 3351 in value
File http://reactnativehost/index.android.bundle
line 94 col 13601 in receiveTouches
File http://reactnativehost/index.android.bundle
line 94 col 12809 in Re
File http://reactnativehost/index.android.bundle
line 94 col 12420 in Se
File http://reactnativehost/index.android.bundle
line 94 col 89237 in xe
File http://reactnativehost/index.android.bundle
line 94 col 12969 in [anonymous]
File http://reactnativehost/index.android.bundle
line 94 col 2058 in _
File http://reactnativehost/[native code]
line (unknown) in forEach
File http://reactnativehost/index.android.bundle
line 94 col 12622 in ke
File http://reactnativehost/index.android.bundle
line 94 col 877 in w
File http://reactnativehost/index.android.bundle
line 94 col 582 in T
File http://reactnativehost/index.android.bundle
line 94 col 528 in b
File http://reactnativehost/index.android.bundle
line 94 col 385 in p
File http://reactnativehost/index.android.bundle
line 227 col 5087 in onResponderRelease
File http://reactnativehost/index.android.bundle
line 227 col 6338 in value
File http://reactnativehost/index.android.bundle
line 227 col 7082 in value
File http://reactnativehost/index.android.bundle
line 1003 col 1098 in handleOnPress
File http://reactnativehost/index.android.bundle
line 1401 col 2004 in onPress
File http://reactnativehost/index.android.bundle
line 1401 col 848 in V
```

Any obvious (or less obvious) things I'm missing? 
Thanks

**Comment by waltjones** [comment]
Your config looks correct assuming sourcemap.android.map is in the current directory when you run curl.

You can check settings/source_maps in your Rollbar project dashboard to verify that the source map uploaded successfully and is valid.

If you contact support (support@rollbar.com) they can look at the specific occurrences and source maps on Rollbar's backend and troubleshoot further.

**Comment by mtieltjes** [comment]
Thanks @waltjones .

> assuming sourcemap.android.map is in the current directory when you run curl
Yes, Rollbar shows the same sourcemap as upload result. I've compared them multiple time to verify it was actually the same sourcemap.

I have mailed the support and will report back in this thread whenever I have something to share which might be of interest for others running into similar issues

**Comment by mtieltjes** [comment]
Alright, seems my config was wrong all along;
```js
client: {
  javascript: {
    source_map_enabled: true,
    codeVersion: `${codeVersion}.android`,
  },
},
```
^ `codeVersion` should be `code_version` [as also stated in the docs](https://docs.rollbar.com/docs/source-maps#2-configure-the-rollbarjs-sdk-to-support-source-maps).

Thanks for the quick help, you guys are awesome!
