### ISSUE TITLE
not working with expo build apk

### ISSUE THREAD

**Issue by LinarAI** [rollbar/rollbar-react-native#131]
I am a new user will roll bar. I have tried your rollbar-react-native and follow the instrucions with code in App.js. it works fine with expo. but when i run expo build:android -t apk and install the app on my android phone, it doesn't work. I stuck here several days.  Is it necessary to also add the android sdk? could you help me with this?

**Comment by LinarAI** [comment]
i got it, rollbar don't support expo cli

**Comment by waltjones** [comment]
Rollbar-react-native depends on Rollbar.js (npm package 'rollbar'). Try updating to latest (v2.19.3). This release has a fix that is relevant to expo and may solve your issue. https://github.com/rollbar/rollbar.js/releases/tag/v2.19.3

I just tested here and the apk is working on Android devices.
