### ISSUE TITLE
React Native (Android): Rollbar reports errors properly with rollbar.error() but not when crashing

### ISSUE THREAD

**Issue by lukewlms** [rollbar/rollbar-react-native#138]
### Description

After integrating Rollbar into React Native Android, `rollbar.error(...)` calls do show up on the Bugsnag website, but a forced JS crash does not.

Am I missing something?  The intro docs didn't say any special handling was needed to handle thrown JS errors on Android (and iOS does report both those errors and `rollbar.error` logs).

I'm reproing with a very minimal app.  The thrown error is not reported but the `.error()` is.

### Steps to reproduce
Run the app below.

### Environment
"rollbar-react-native": "^0.9.1",
"react-native": "^0.63.2",

### Example code

```ts
export function App() {
  const rollbar = useMemo(() => new Client(ROLLBAR_API_KEY), []);
  useEffect(() => {
    rollbar.error("Testing rollbar error logging")
    setTimeout(() => {
      throw new Error("testing rollbar crash");
    }, 10000);
  }, []);

  return <View><Text>Hello World</Text></View>;
}

```

**Comment by lukewlms** [comment]
These are showing up now.  Maybe I hadn't fully restarted the app.  Thanks!

**Comment by waltjones** [comment]
Yes, these get queued at crash time, and sent on app restart. Good to hear you got it working.

**Comment by lukewlms** [comment]
Closing, thanks for the quick reply.  Looking forward to using Rollbar!
