### ISSUE TITLE
Missing `captureDeviceInfo` property on type ConfigurationOptions

### ISSUE THREAD

**Issue by hsingh6764** [rollbar/rollbar-react-native#142]
Missing `captureDeviceInfo` property on interface ConfigurationOptions inside `index.d.ts`. 

Docs: 
- https://github.com/rollbar/rollbar-react-native/blob/4bcf59c593cba1c9e6bbb80ce7bdecec467e8d3a/index.d.ts#L32
- https://github.com/rollbar/rollbar-react-native/blob/4bcf59c593cba1c9e6bbb80ce7bdecec467e8d3a/src/Rollbar.js#L122

**Comment by sampie777** [comment]
Maintainers, please solve this issue. There's a PR with only one line of code changes. Should be quick to review ;)

**Comment by waltjones** [comment]
PR is merged. Will release asap.

**Comment by waltjones** [comment]
Released in v0.9.3. https://github.com/rollbar/rollbar-react-native/releases/tag/v0.9.3
