### ISSUE TITLE
Use of undeclared identifier 'RollbarReactNative'

### ISSUE THREAD

**Issue by SohaibKtb** [rollbar/rollbar-react-native#148]
Hello @waltjones,

I have this error on Archive build on Xcode using Macbook with M1 chip:
`Use of undeclared identifier 'RollbarReactNative'`

```jsx
    "react-native": "^0.63.4",
    "rollbar-react-native": "^0.9.2"
```

I am using flipper version: '0.91.2' => latest one

it is happening at this line:
```jsx
[RollbarReactNative initWithAccessToken:@"f76f58a3axxxxxxxxxxxxxx"];
```

Of course I added this line `#import <RollbarReactNative/RollbarReactNative.h>` at the top of AppDeletgate.m file

I checked the Pods folder, only the Rollbar folder is added, but there is no folder called RollbarReactNative.

Do you know why?

thanks for your help.

**Comment by pulkitsharmac24** [comment]
same issue

**Comment by shoespray** [comment]
+1

**Comment by waltjones** [comment]
I'll try to repro tomorrow, and reply here with what I see.

**Comment by pulkitsharmac24** [comment]
It was a mistake on our end.

we mistakenly added the import below "#ifdef FB_SONARKIT_ENABLED" in AppDelegate.m file.

we moved the import above this line and our build compiled successfully.

**Comment by SohaibKtb** [comment]
thanks @pulkitsharmac24
