### ISSUE TITLE
iOS Build Errors

### ISSUE THREAD

**Issue by Kyonru** [rollbar/rollbar-react-native#156]
Does this library support RN 0.67.2? App can't build on Xcode after:
```bash
yarn add rollbar-react-native
pod install
```

RN version: 0.67.2 (using an M1 Mac).

Error:
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FlipperKitNetworkPlugin", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_SKIOSNetworkAdapter", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_FlipperKitReactPlugin", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_FlipperClient", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_SKDescriptorMapper", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_FlipperKitLayoutPlugin", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_RCTBridge", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_RCTBundleURLProvider", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_FKUserDefaultsPlugin", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_RCTRootView", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Undefined symbol: _OBJC_CLASS_$_FlipperKitNetworkPlugin

Undefined symbol: _OBJC_CLASS_$_SKIOSNetworkAdapter

Undefined symbol: _OBJC_CLASS_$_FlipperKitReactPlugin

Undefined symbol: _OBJC_CLASS_$_FlipperClient

Undefined symbol: _OBJC_CLASS_$_SKDescriptorMapper

Undefined symbol: _OBJC_CLASS_$_FlipperKitLayoutPlugin

Undefined symbol: _OBJC_CLASS_$_RCTBridge

Undefined symbol: _OBJC_CLASS_$_RCTBundleURLProvider

Undefined symbol: _OBJC_CLASS_$_FKUserDefaultsPlugin

Undefined symbol: _OBJC_CLASS_$_RCTRootView

Removing Rollbar fixes the build.
```bash
yarn remove rollbar-react-native
pod install
```

**Comment by teivienn** [comment]
It helped me
https://github.com/aiba/react-native-m1/blob/main/README.md

**Comment by waltjones** [comment]
v1.0.0-beta.0 is now available. https://github.com/rollbar/rollbar-react-native/releases/tag/v1.0.0-beta.0

This is expected to be fully compatible with iOS build targets, as well as web-only targets and [@rollbar/react](https://www.npmjs.com/package/@rollbar/react). Please report any issues. Note that there are breaking changes between v0.9.3 and this 1.0.0 beta. See the [updated SDK guide](https://docs.rollbar.com/docs/react-native) and the [migration guide](https://docs.rollbar.com/docs/migrating-to-v100) for details.
