### ISSUE TITLE
[iOS] RollbarReactNative/RollbarReactNative.h file not found

### ISSUE THREAD

**Issue by fryossi** [rollbar/rollbar-react-native#16]
`RollbarReactNative/RollbarReactNative.h:6:9: fatal error: 'Rollbar/Rollbar.h' file not found
#import <Rollbar/Rollbar.h>`

react-native: 0.52.0
react: 16.2.0
rollbar-react-native: 0.2.0-alpha3
Rollbar.framework: latest

Am i missing something?
Thanks!

**Comment by fryossi** [comment]
Sorry, found the problem- I'm using [react-native-schemes-manager](https://github.com/blargity/react-native-schemes-manager). Forgot to run `react-native-schemes-manager all`.

**Comment by fryossi** [comment]
I'm using CircleCI and i can't build the app. After adding the Rollbar.framework locally there's no problem but on the CI server it won't work.

**Comment by doronnahum** [comment]
I have the same problem, only on CI server, local work fine.

**Comment by rivkahstandig3636** [comment]
Thanks for reporting this issue. We'll investigate.

**Comment by rokob** [comment]
Okay, there is a new release up of the rollbar-ios library (https://github.com/rollbar/rollbar-ios/releases/tag/v1.0.0-alpha6) with a new zip file.

In a normal iOS app you would need to add `libc++` to your link binary with libraries phase and add `-ObjC` to your "Other Linker Flags" section. However both of these should already be there in React Native, but if you get any weird C++ errors or missing selector exceptions then double check those two things.

There was a problem with the build process that generated the framework binary that I believe is now fixed. I'm going to leave this open issue for a bit in case other problems arise.

**Comment by fryossi** [comment]
Thanks- Works.
I had to fork and add Rollbar.framework to the repo in order to be able to build on CI server.

**Comment by dwilt** [comment]
@rokob I'm currently getting this now too with `0.2.0-alpha3`:

![image](https://user-images.githubusercontent.com/1065539/37155216-9b80a824-22e2-11e8-9861-4543065cf34d.png)

I'm trying to install `1.0.0-alpha6` but getting this:

```
Dans-MacBook-Pro:ios dwilt$ yarn add rollbar-react-native@1.0.0-alpha6
yarn add v1.3.2
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "rollbar-react-native" that matches "1.0.0-alpha6"
? Please choose a version of "rollbar-react-native" from this list: 
  0.2.0-alpha3 
  0.2.0-alpha1 
  0.1.3-alpha3 
  0.1.3-alpha2 
  0.1.3-alpha1 
  0.1.2 
  0.1.1 
❯ 0.1.0 
Dans-MacBook-Pro:ios dwilt$ 
```
Any ideas?

**Comment by cihadturhan** [comment]
I'm using `v1.0.0-alpha6`, checked `libRollbarReactNative.a` exists under "Link Binary with Libraries" section and I checked `-ObjC` exists in "Other Linker Flags" but still, I have this issue.
Do you have any other suggestions?

**Comment by zjullion** [comment]
As per https://github.com/rollbar/rollbar-react-native/issues/22, adding Rollbar.framework in node_modules is not ideal, as you really shouldn't be checking node_modules into source control.  I've found that adding Rollbar.framework to the project instead (I threw it under the 'iOS' folder) and adding  it in Xcode to "Link Binary with Libraries" will solve this issue.

**Comment by rokob** [comment]
As of 0.3.0 you should no longer need to add the Rollbar framework as a dependency, things should just work.

**Comment by jaimeagudo** [comment]
I finally fixed the error that  it on these versions

package.json
```
"react-native": "0.57.3",
"rollbar-react-native": "^0.3.3",
```

Xcode Version 10.1 (10B61))

In Xcode, pick your target, go to `BuildSettings->HEADER_SEARCH_PATHS`

Add
`$(SRCROOT)/../node_modules/rollbar-react-native/ios/rollbar-ios/Rollbar/`
