### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by BlueBazze** [rollbar/rollbar-react-native#162]
Was just going implementing rollbar into our app.
Noticed that the last commit is almost a year ago.
Has this package been deprecated?

Also during setup of this package.
We dont have access to make some of the native part changes with Expo. - And cant see why they would be neccessary for the user to make.

Took a look at the reactjs package you have.
It seems to use browser specific code. So im guessing it is not viable for RN.

So are we supposed to use the rollbar.js package instead?

**Comment by waltjones** [comment]
v1.0.0-beta.0 is now available. https://github.com/rollbar/rollbar-react-native/releases/tag/v1.0.0-beta.0

This is expected to be fully compatible with iOS build targets, as well as web-only targets and [@rollbar/react](https://www.npmjs.com/package/@rollbar/react). Please report any issues. Note that there are breaking changes between v0.9.3 and this 1.0.0 beta. See the [updated SDK guide](https://docs.rollbar.com/docs/react-native) and the [migration guide](https://docs.rollbar.com/docs/migrating-to-v100) for details.
