### ISSUE TITLE
[Android] Rollbar: Native Client not found.

### ISSUE THREAD

**Issue by vivekverma1993** [rollbar/rollbar-react-native#17]
I tried adding react-native-rollbar and i am facing issues in both android and ios. Issue with ios is already an open issue and in android its seems RollbarReactNativePackage should be a public class as its not importable in MainApplication.java right now. That is why linking is not working and we are unable to add RollbarReactNativePackage inside createAdditionalReactPackages()

**Comment by rivkahstandig3636** [comment]
@rokob Can you please take a look at this?

**Comment by rokob** [comment]
Why would you import `RollbarReactNativePackage` and what is `createAdditionalReactPackages`?

**Comment by vivekverma1993** [comment]
Sorry for the confusion here, i am using react-native-navigation which requires to list all react native packages to list under a method called createAdditionalReactPackages. In General every library make their react native packages importable by making it a public class, so that it cannot restrict it usability.

**Comment by vivekverma1993** [comment]
@rokob  any update on this?

**Comment by jessewgibbs** [comment]
@vivekverma1993 we're still working on this but having a hard time reproducing the problem.  Can you confirm that this is still a problem for you?

**Comment by vivekverma1993** [comment]
Yes its still a problem.
