### ISSUE TITLE
[iOS] ld: framework not found Rollbar for architecture x86_64

### ISSUE THREAD

**Issue by DanPGill** [rollbar/rollbar-react-native#18]
After having the problem from this issue - https://github.com/rollbar/rollbar-react-native/issues/12#issuecomment-368114085 - and upgrading my `Rollbar.framework` to the version from this release (v1.0.0-alpha6) and following the steps in the linked comment (adding `libc++` to my linked binary and making sure `-ObjC` was in my Other Linker Flags) I get the above error in Xcode. The steps I took are as follows:

1) Add package using `yarn add`
2) Link package
3) Add (new) Framework to workspace
4) Add relevant lines to Podfile and run pod install
5) Build => error ld: framework not found Rollbar for architecture x86_64

Any ideas about what I might have missed or done wrong? Thanks.

**Comment by rokob** [comment]
Are you using Cocoapods or did you add the framework to be linked in the relevant project?

**Comment by otusweb** [comment]
I have the same issue. I'm not using cocoapods.

Here are the errors I get:
```
ld: warning: Auto-Linking supplied '/Users/otusweb/Projects/Wazza/mobile-app-wazza/node_modules/rollbar-react-native/ios/Rollbar.framework/Rollbar', framework linker option at /Users/otusweb/Projects/Wazza/mobile-app-wazza/node_modules/rollbar-react-native/ios/Rollbar.framework/Rollbar is not a dylib
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Rollbar", referenced from:
      objc-class-ref in libRollbarReactNative.a(RollbarReactNative.o)
     (maybe you meant: _OBJC_CLASS_$_RollbarReactNative)
  "_OBJC_CLASS_$_RollbarConfiguration", referenced from:
      objc-class-ref in libRollbarReactNative.a(RollbarReactNative.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by joshdhenry** [comment]
I'm getting the same errors as you, @otusweb . I've tried manually adding alpha v7, alpha v6, and I've tried installing via cocoa pods but I still get these errors.

I've added libc++.dylib from /usr/lib in the "Link Binary With Libraries" section of Build Phases for the main target. 

I've also verified -ObjC exists in the "Other Linker Flags" field of Build Settings for the main target.

**Comment by fernandofranca** [comment]
I'm in the same situation as @otusweb.

**Comment by DanPGill** [comment]
Sorry for the late reply, I've tried both manually adding the framework and using Cocoapods with the same results.

**Comment by rokob** [comment]
There is a new release v0.3.0 that does not require adding the framework for rollbar-ios, setting the dependency `"rollbar-react-native": "0.3.0"` and running `react-native link rollbar-react-native` should be all the is necessary to get iOS to work.

**Comment by justinhandley** [comment]
Unfortunately the new version doesn't fix this - I'm still experiencing this with 0.3.2 and just linking.
