### ISSUE TITLE
Build Failure with React Native and Rollbar Integration - ‘RollbarCrash’ Module Issues

### ISSUE THREAD

**Issue by tawanorg** [rollbar/rollbar-react-native#202]
## Description

I'm encountering build failures when integrating Rollbar into a bare-minimum React Native project. The error seems to stem from the `RollbarCrash` module, causing build failures in both the terminal and Xcode workspace.

## Steps to Reproduce:

1. Create a new React Native project with the following configuration:
    - **React Native version**: 0.76.0
    - **Rollbar version**: 1.0.0-beta.4
2. Install Rollbar dependencies by following the official Rollbar integration steps for React Native.
3. Attempt to build the project using:
    - `react-native run-ios` in the terminal
    - Opening the `.xcworkspace` in Xcode and building from there.

## Expected Behavior

The project should build successfully with Rollbar integrated.

## Actual Behavior

The build fails after installing Rollbar. Below are the specific errors from Xcode:
`Module ‘RollbarCrash.RollbarCrashThread’ requires feature ‘objc’` and more

This error is repeated multiple times for various symbols within `RollbarCrash`. The project builds without Rollbar installed, but after adding the Rollbar dependencies, neither the terminal nor Xcode will build the project successfully.

Please see the attached screenshots of the error messages in Xcode and the terminal for more details:

![image (3)](https://github.com/user-attachments/assets/67774cae-ebe3-41f3-844e-92362d391aad)
![image (2)](https://github.com/user-attachments/assets/c212f5aa-96cc-46ab-93d0-505f11d45526)
![image (1)](https://github.com/user-attachments/assets/202c875e-5caf-4c5d-978e-653639a3e8ea)
![image](https://github.com/user-attachments/assets/b5f415f6-8b62-463a-8bea-eb593a3333d1)

## Dependencies:

```json
"dependencies": {
  "@rollbar/react": "^0.12.0-beta",
  "react": "18.3.1",
  "react-native": "0.76.0",
  "rollbar": "^2.26.4",
  "rollbar-react-native": "^1.0.0-beta.4"
}
```

## Environment

- **Xcode version**: `16`
- **macOS version**: `15.0.1`
- **Node version**: `20.15.1`

## Podfile Configuration:

```
platform :ios, '11.0'
use_frameworks! :linkage => :static

target 'AppName' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath]
  )

  # Rollbar dependencies
  pod 'RollbarReport'
  pod 'RollbarCrash', :modular_headers => true

  target 'YourAppNameTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end

**Comment by matux** [comment]
@tawanorg I'm looking into this right now, I'll try to get a fix asap. Thank you so much for this.

**Comment by matux** [comment]
@tawanorg So, the problem here is two-fold:

1. Don't define these pod dependencies separately:
```
  # Rollbar dependencies
  pod 'RollbarReport'
  pod 'RollbarCrash', :modular_headers => true
```
Cocoapods suggests this when using dynamic framework linkage, but the suggestion is wrong. So delete those two lines.

2. Unlike the *Podfile Configuration* you shared in the issue, the `Podfile` in the repository you shared is not correctly defining static framework llinkage. 
You have to either do this explicitly by adding the `use_frameworks! :linkage => :static` line, or set `USE_FRAMEWORKS = 'static'` in `.xcode.env`, which in your repository example is set to `true` which ends up doing dynamic linking.

**Comment by matux** [comment]
@tawanorg Nevermind my last reply, I can see that's not the source of the problem. I believe I've found a solution and will do my best to release today.

**Comment by matux** [comment]
@tawanorg Please refer to this comment for the solution: https://github.com/rollbar/rollbar-react-native/issues/199#issuecomment-2438670310

**Comment by matux** [comment]
I'll close this issue as soon as you confirm you got things working on your side. Any other issue you're seeing, don't hesitate communicating, I'll do my best to fix things asap for you.

**Comment by rarenatoe** [comment]
If I don't add `pod 'RollbarCrash', :modular_headers => true` to the Podfile, I get 
```[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `RollbarReport` depends upon `RollbarCrash`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.```

this is even in version 1.0.0-beta.5

**Comment by matux** [comment]
I'm closing this issue as this should be fixed in the latest release. Feel free to reopen or leave a comment if you still see the same issues!

**Comment by rarenatoe** [comment]
Will we be able to avoid `use_frameworks! :linkage => :static` when it's out of beta?
