### ISSUE TITLE
Missing '#include <sys/_types/_ucontext64.h>'; 'ucontext64_t' must be declared before it is used 

### ISSUE THREAD

**Issue by teivienn** [rollbar/rollbar-react-native#206]
When creating a build on ios I get a problem after upgrading to the latest version of xcode. In the file `RollbarCrashMachineContext.c`

import `#include <sys/_types/_ucontext64.h>` is missing

I had a similar problem with [sentry](https://github.com/getsentry/sentry-cocoa/pull/4244/files) and adding the same import fixed the build problem.

**Comment by davevilela** [comment]
@teivienn any updates? did you get it sorted?

**Comment by teivienn** [comment]
After some time of debugging, it turns out the problem was in my podfile. If you upgrade to beta-5 you should not have this problem.  this import is already in the sdk for ios [rollbar-apple](https://github.com/rollbar/rollbar-apple/blob/2077a05788a740eea7d804c293c7d5313169b5ed/RollbarNotifier/Sources/RollbarCrash/Util/RollbarCrashMachineContext.c#L42)

In general I am confused that the correct versioning is not followed and beta-N versions have the latest tag in npm🙁

@davevilela If you still have this problem I will leave this issue open, if not I would like to close it
