### ISSUE TITLE
Disabling crash reporting doesn't work

### ISSUE THREAD

**Issue by otusweb** [rollbar/rollbar-react-native#21]
I'm using another crash reporting framework and thus don't need the one from rollbar. How can I disable it?

**Comment by cihadturhan** [comment]
Actually there is a config to disable, but unfortunately it doesn't work 😞 

I tried the following but I still see the reports going to dashboard:
```javascript
//__DEV__ constant lets me know in which environment I'm working on
{
      enabled: !__DEV__, 
      payload: {
        environment: __DEV__ ? "development" : "production",
        client: {
          ....
        }
      },
};
```
@rivkahstandig3636 Should I open a new issue for that ?

**Comment by cihadturhan** [comment]
Anyway, I found a workaround which does the job. I'm sharing my code for the ones need that:

```javascript
  const fullConfig = {
      enabled: !__DEV__, // NOTE - enabled is not working
      verbose: false, //Set true if you need to see it in console
      payload: {
        environment: __DEV__ ? "development" : "production",
        client: {
          javascript: {
            source_map_enabled: true,
            code_version: `${DeviceInfo.getVersion()}.${Platform.OS}`,
          }
        }
      },
      logLevel: 'info', // assign rollbar.log as rollbar.info
      reportLevel: 'info', //send this level or above
      ...extraConfig
  };
  const rollbarConfig = new Configuration(ROLLBAR_CLIENT_KEY, fullConfig);

  this.instance = new Client(rollbarConfig);
  //There is a bug that `enabled` doesn't work. Manually configure it
  this.instance.rollbar.configure({enabled: fullConfig.enabled});
```

**Comment by rivkahstandig3636** [comment]
@cihadturhan, yes, if you wouldn't mind opening an issue for the bug you found that would be great!

**Comment by rivkahstandig3636** [comment]
Actually, I forgot I can just edit the title of an issue. No need to open a new one.

**Comment by rokob** [comment]
enabled should work correctly as of 0.3.0

**Comment by ajaykumar97** [comment]
Hello Guys!
I am not able to disable the logs reporting for the development. Can anyone please let me know how can I do that?

My config:

"rollbar-react-native": "^0.9.1"
"react-native": "0.63.3"

I have tried the following code:

```
export const rollbar = new Client(config.ROLLBAR_TOKEN, {
  enabled: false,
});
```
