### ISSUE TITLE
manually adding iOS rollbar framework adds it node_module folder

### ISSUE THREAD

**Issue by otusweb** [rollbar/rollbar-react-native#22]
It's not recommended to keep the node_modules folder under source control. 
So checking out the project breaks the rollbar integration. 

Is there a way to add the framework automatically so that automated build can work?

**Comment by rokob** [comment]
Yeah there might be a way, npm does not handle bundling normal iOS frameworks with js packages, that is why the instructions are the way they are. I think I have the issue mostly figured out so I will try to see if I can get that bundling to happen automatically instead.

**Comment by rokob** [comment]
As of 0.3.0 this is resolved
