### ISSUE TITLE
Question: Is the native integration needed if all we want is to log JS side error

### ISSUE THREAD

**Issue by otusweb** [rollbar/rollbar-react-native#23]
I'm having issue installing the iSO plugin and thus i'm wondering if i even need to. I don't have any native code, I'm using another crash reporting service.

Do i need to install teh native part or could i get away with only the JS side of the instructions?

**Comment by rokob** [comment]
You can use rollbar.js directly by using rollbar.js as a dependency and importing it via `import Rollbar from 'rollbar/src/react-native/rollbar';`.

**Comment by otusweb** [comment]
Works thanks.
When using this way will rollbar catch unhandled exceptions?

**Comment by rokob** [comment]
It will not handle exceptions in native code if you do it that way. If you have an uncaught javascript exception, uh it will probably not get caught correctly as it will crash the runtime, at least in production.
