### ISSUE TITLE
Uploaded sourcemaps doesn't show the stacktrace of source 

### ISSUE THREAD

**Issue by cihadturhan** [rollbar/rollbar-react-native#24]
I've successfully integrated rollbar-react-native and see all events on the dashboard.
However, under the `Traceback` tab I see the following stack trace

https://gist.github.com/cihadturhan/e85c71bc3d888d1c08865c28c06eb657

and I wrote the following script to upload my sourcemap and use version from package.json:
(feel free to use)

```sh
#!/bin/bash
react-native bundle \
  --platform android \
  --dev false \
  --entry-file index.js \
  --bundle-output outputs/index.android.bundle \
  --sourcemap-output outputs/sourcemap.android.js \
  --sourcemap-sources-root ./

version=`node scripts/\version.js`

curl https://api.rollbar.com/api/1/sourcemap \
  -F access_token=XXXXXXXXXXXXXXXXXXXXX \
  -F version=$version.android \
  -F minified_url=http://reactnativehost/index.android.bundle \
  -F source_map=@outputs/sourcemap.android.js \
  -F index.js=@index.js
```

and here is the full output: 
```
Scanning folders for symlinks in C:\Users\cihad\Desktop\github\ptt-finans\PttFinans\node_modules (48ms)
Scanning folders for symlinks in C:\Users\cihad\Desktop\github\ptt-finans\PttFinans\node_modules (50ms)
Loading dependency graph, done.
bundle: start
bundle: finish
bundle: Writing bundle output to: outputs/index.android.bundle
bundle: Writing sourcemap output to: outputs/sourcemap.android.js
bundle: Done writing sourcemap output
bundle: Done writing bundle output
Assets destination folder is not set, skipping...
{
  "err": 0,
  "result": "2.0.11.android"
}
```
I can find the upload file on the rollbar settings page successfully:
![image](https://user-images.githubusercontent.com/3739536/37626202-042a6f44-2be0-11e8-9207-e72a9e1440ec.png)

I also logged my config object to crosscheck versions:

```json
{
  "verbose": true,
  "payload": {
    "environment": "production",
    "client": {
      "javascript": {
        "source_map_enabled": true,
        "code_version": "2.0.11.android"
      }
    }
  },
  "logLevel": "info",
  "reportLevel": "debug"
}"
```

Still, I see line numbers from bundled javascript file. Can you give any pointers to resolve this issue?
Let me know if I can help further to resolve this issue.

**Comment by rivkahstandig3636** [comment]
Hi @cihadturhan, thanks for the report. We'll take a look and get back to you.

**Comment by cihadturhan** [comment]
Thanks for letting me know, @rivkahstandig3636, I already contacted with your online support.

**Comment by jfbaraky** [comment]
@cihadturhan Any solutions? I'm having the same problem.

**Comment by cihadturhan** [comment]
Unfortunately I couldn't get any help from support team. I'm using rollbar as the project owner strongly suggested but it's still in Alpha stage as they mentioned in the readme. 

You can use `sourcemap-lookup` or similar node packages to manually find the correct line number in the source. I had to do it eventually.

**Comment by rokob** [comment]
Hey, I'm still trying to figure out where this breaks down with the production build on Android and the generation of the source map. I will dig into this right now and try to get you something usable by tomorrow at the latest.

**Comment by rokob** [comment]
Okay so I've got a fix out to take care of part of this on the backend. There was a bit of a mixup with how we are handling source mapping for javascript that does not come from the browser and server-side node environments.

However, sadly you will soon come back to say great things are getting unminified but they are pointing to the wrong lines. This is a bug in the React Native bundler: https://github.com/facebook/react-native/issues/6946

So the fix for the backend will be up soon and I will update here to close this when that is out, but you may still see some weirdness with production Android because of the upstream bundler problems.

**Comment by cihadturhan** [comment]
Hey @rokob 
I'd like to say that the issue happens because of file extension. I realized you require `.map` extension for [regular web projects](https://docs.rollbar.com/docs/source-maps#section-recommended-method-upload-pre-deploy). In readme, you wrote `.js` extension and that doesn't work for sourcemaps. 

Before
![image](https://user-images.githubusercontent.com/3739536/40049979-db729bd6-583e-11e8-958f-bdcc760ee752.png)

After
![image](https://user-images.githubusercontent.com/3739536/40080819-d98c0ef0-5894-11e8-8026-49afe6587ca9.png)

As you can see the screenshots, it works properly when I provide a `.map` file. I'm planning to update the readme file and send a PR for you.
