### ISSUE TITLE
Only collect person.id by default for person tracking

### ISSUE THREAD

**Issue by rivkahstandig3636** [rollbar/rollbar-react-native#39]
Allow the ability to send person.email and person.username, but by default we should only collect person.id going forward.

@rokob This is a top priority.

**Comment by gusgard** [comment]
Any update on this?

**Comment by rokob** [comment]
setPerson works, if you call setPerson with the specified data then it will all get passed along. This only is relevant for automatically captured person data so is not relevant here.

**Comment by gusgard** [comment]
Doesn't work for me, @rokob do you have a working example? 

```
const rollbar = new Client(config);
rollbar.setPerson(id, name, email); 
console.log(rollbar.config.payload); ---> person is emptry!
```
