### ISSUE TITLE
Doesn't work at all - Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by Solitaryo** [rollbar/rollbar-react-native#43]
I installed rollbar and rollbar-react-native.
Then I link the library:
`react-native link rollbar-react-native`
And then add the Rollbar.framework inside RollbarReactNative.xcodeproj, but nothing works.

This is the error:
`
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Rollbar", referenced from:
      objc-class-ref in libRollbarReactNative.a(RollbarReactNative.o)
     (maybe you meant: _OBJC_CLASS_$_RollbarReactNative)
  "_OBJC_CLASS_$_RollbarConfiguration", referenced from:
      objc-class-ref in libRollbarReactNative.a(RollbarReactNative.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

Is there something I can do to fix this problem?

**Comment by Solitaryo** [comment]
More info, we are using:
"react": "16.0.0",
"react-native": "0.50.3",
"rollbar": "2.3.9",
"rollbar-react-native": "0.2.0-alpha4"

System:
MacOS High Sierra 10.13.4.
Macbook Pro Mid 2015

**Comment by darkmantle** [comment]
I am having the same issue, any news?

**Comment by azamkth** [comment]
same issue any help?

**Comment by rokob** [comment]
I have had trouble reproducing this, trying again right now, will update soon.

**Comment by rokob** [comment]
Alright I've got this reproducing, I have one fix but it is ugly so trying to work out something more principled.

**Comment by rokob** [comment]
There is a new release v0.3.0 that does not require adding the framework for rollbar-ios, setting the dependency `"rollbar-react-native": "0.3.0"` and running `react-native link rollbar-react-native` should be all the is necessary to get iOS to work.

**Comment by nschild** [comment]
I think I am getting this same error:

    The following build commands failed:
   	CompileC /..../Build/Intermediates.noindex/ArchiveIntermediates/..../IntermediateBuildFilesPath/Pods.build/Release-iphoneos/Rollbar.build/Objects-normal/arm64/KSString.o Rollbar/KSCrash/Source/KSCrash/Recording/Tools/KSString.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler

I can build locally but on AppCenter, it fails.
rollbar-react-native: ^0.5.0
xcode version: 10.2.1
appcenter: node v8 local: node v11 (currently rebuilding on appcenter v10)

I did not install with the rollbar framework, as per my understanding it is not required anymore.
