### ISSUE TITLE
Unable to compile... Framework not found for iOS 

### ISSUE THREAD

**Issue by alexdunae** [rollbar/rollbar-react-native#44]
I added the framework per the readme but am getting the following error:

```
ld: framework not found Rollbar for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Our setup...

```
"react-native": "0.55.3",
"react": "^16.0.0-alpha.6",
"rollbar-react-native": "^0.2.0-alpha4",
```

**Comment by rokob** [comment]
There is a new release v0.3.0 that does not require adding the framework for rollbar-ios, setting the dependency `"rollbar-react-native": "0.3.0"` and running `react-native link rollbar-react-native` should be all the is necessary to get iOS to work.
