### ISSUE TITLE
Unable to run on Android

### ISSUE THREAD

**Issue by darkmantle** [rollbar/rollbar-react-native#49]
Whenever I run on Android I get the following error (iOS works perfectly fine with 0.3.0).

"Attempt to invoke virtual method 'void com.rollbar.android.Rollbar.configure(com.rollbar.notifier.config.ConfigProvider)' on a null object reference'

StackTrace poitns to RollbarReactNative.java:492

My code (minus API key) is:

```javascript
const rollbarConfig = new Configuration("lolno", {
    captureUncaught: true,
    captureUnhandledRejections: true,
    payload: {
        environment: "debug"
    }
});
const rollbar = new Client(rollbarConfig);
```

**Comment by rokob** [comment]
I can reproduce this by not calling Rollbar.init in the onCreate method of the MainApplication. However, https://docs.rollbar.com/docs/react-native#section-android has that you need to call this in your MainApplication. It might be a little buried in the docs.

**Comment by marcojr** [comment]
It's probably missing on your MainApplication.java

@Override
public void onCreate() {
  super.onCreate();
  RollbarReactNative.init(this, "POST_CLIENT_ITEM_ACCESS_TOKEN", "production");
  ...
}

**Comment by felansu** [comment]
@marcojr you work with firebase & react-redux?

**Comment by mhb-yt** [comment]
I am using the [Custom Development Client](https://docs.expo.dev/development/introduction/) and having the same issue on Android? And you can't modify MainApplication.java there. Does anyone have a solution?
