### ISSUE TITLE
Does Rollbar React Native support telemetry?

### ISSUE THREAD

**Issue by RollbarExample** [rollbar/rollbar-react-native#51]
Hi,
Does Rollbar React Native support telemetry?

Thanks

Wahid Ali.

**Comment by rivkahstandig3636** [comment]
Hi Wahid, Not yet! You can follow along on this issue for further updates: https://github.com/rollbar/rollbar-react-native/issues/27

**Comment by ericpolkadoc** [comment]
Hi -- has Telemetry been added to React Native Rollbar?  In our sessions I am not seeing them for react native errors

Also, I am somehow I am seeing a react.js error in my list of errors.  The Telemetry does show for this error.

In the first image you can see the top one is a JS log, the rest are react native.  How is the top one a JS error and not identified as react native?

The 2nd image shows what is being received for telemetry for the errors tagged in the list as react native

![image](https://user-images.githubusercontent.com/13222265/167684286-5abbe08a-0255-4512-813f-1c7843c8357a.png)

![image](https://user-images.githubusercontent.com/13222265/167685470-0fb9158c-9c5d-4ed9-9926-c6d21cef737e.png)
