### ISSUE TITLE
Error linking project 

### ISSUE THREAD

**Issue by lhrolim** [rollbar/rollbar-react-native#53]
Following the getting started instructions I got the bellow error:

```
react-native link rollbar-react-native
Scanning folders for symlinks in /home/luiz/workspace/qb_app/node_modules (16ms)
rnpm-install ERR! Something went wrong while linking. Error: Maximum call stack size exceeded 
Please file an issue here: https://github.com/facebook/react-native/issues 

Maximum call stack size exceeded
```

I have the following versions:

react-native: 0.56
node: v10.7.0
npm: 6.3.0

Meanwhile Is there a manual guideline for android available?

**Comment by rivkahstandig3636** [comment]
Thanks for the bug report! As for your android question, there is not, but we will look into creating one. Sorry about that.
