### ISSUE TITLE
React native link failed

### ISSUE THREAD

**Issue by vyrruss** [rollbar/rollbar-react-native#58]
Hey,

I try to add rollbar to my react-native app but seems not to work by just adding the dependency and doing the `react-native link rollbar-react-native`.

Below the error I'm having after the build.

<img width="453" alt="screen shot 2018-10-11 at 09 55 18" src="https://user-images.githubusercontent.com/8026576/46789007-cb289880-cd3b-11e8-9f76-203594b2208f.png">

react-native: 0.55.4
rollbar-react-native: ^0.3.3

**Comment by markronquillo** [comment]
is this on Android?

**Comment by vyrruss** [comment]
No for ios

**Comment by jessewgibbs** [comment]
@rokob any suggestions here?

**Comment by lnavry** [comment]
@rokob @rivkahstandig3636 I have that issue too and it's kind of a blocker.

@jessewgibbs did you find some solution by any chance?

**Comment by rokob** [comment]
I created a fresh react native app with

```
  9   "dependencies": {
 10     "react": "16.3.1",
 11     "react-native": "0.55.4",
 12     "rollbar-react-native": "^0.3.3"
 13   },
```

Besides running `yarn` the only other thing I ran was `react-native link rollbar-react-native`. 

In my App.js I have:

```
import { Client } from 'rollbar-react-native'
const rollbar = new Client('my_access_token');
```

Running `react-native run-ios` works just fine and calling methods on that constructed `rollbar` instance logs items to Rollbar.

The only other time I've seen issues like this it was usually resolved by deleting the build cache and sometimes blowing out `node_modules`. This isn't really an issue with this library, this is a react native platform problem.

**Comment by jessewgibbs** [comment]
@vyrruss please see the comment above.  I'm going to close this issue, but if you continue to encounter the problem, please comments and reopen it.

**Comment by pe1o2pl** [comment]
same error but on android

```
"react": "16.4.1",
"react-native": "0.56.0",
"rollbar-react-native": "^0.3.3"
```


![screenshot_20181107-163632](https://user-images.githubusercontent.com/14976192/48143827-ebeafc00-e2af-11e8-99a5-4fa20cb88b86.png)

**Comment by dev-z** [comment]
![rollbar_error](https://user-images.githubusercontent.com/8604312/48883488-0db6b800-ee46-11e8-972f-e60782728703.png)
Same error on Android
