### ISSUE TITLE
Gradle 4.4 - Deprecation Warnings

### ISSUE THREAD

**Issue by jessedoyle** [rollbar/rollbar-react-native#59]
Hello!

We've noticed deprecation warnings from our Android build after installing and linking this package in our app.

Here's the specific warnings we're noticing:

```
> Configure project :rollbar-react-native
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
```

We're using Gradle version 4.4 and Android Gradle Plugin 3.2.1. 

I'd be happy to submit a PR to fix these deprecation warnings. What do you think?

**Comment by jessewgibbs** [comment]
@jessedoyle thanks for bringing this to our attention.

@rokob what do you think?

**Comment by rokob** [comment]
I'd be happy to merge a PR that fixes these warnings.

**Comment by jessedoyle** [comment]
@rokob - I've submitted this PR to fix the deprecation warnings: https://github.com/rollbar/rollbar-react-native/pull/63
