### ISSUE TITLE
CocoaPods error

### ISSUE THREAD

**Issue by andrei0807** [rollbar/rollbar-react-native#66]
I got error CocoaPods could not find compatible versions for pod "Rollbar":
In Podfile:
    RollbarReactNative(from '../node_modules/rollbar-react-native') was resolved to 0.4.0 which depends on
     Rollbar(~> 1.4.2)

**Comment by jessewgibbs** [comment]
Hey @andrei0807,

We're catching up after the holiday break.  Is this still an issue for you?

**Comment by jessewgibbs** [comment]
I'm closing this due to no response.  If it's still a problem, please re-open and let us know.

**Comment by TiagoGouvea** [comment]
I'm facing the same problem `CocoaPods could not find compatible versions for pod "Rollbar"` > commented on #87
