### ISSUE TITLE
installing rollbar-react-native

### ISSUE THREAD

**Issue by novose** [rollbar/rollbar-react-native#7]
Hello,

I need to use rollbar for react-native app and it doesn't work. I have installed the package with npm and i have linked it with the link command. But I have an error with the `import com.rollbar.RollbarReactNative;`  in the `MainApplication.java` file, it says :

> C:\IsefacElearningApp\android\app\src\main\java\com\isefacelearningapp\MainApplication.java:6:
>  error: package com.rollbar does not exist
> import `com.rollbar.RollbarReactNative;

So it's something wrong with the package or the installation.

By the way, it's missing something in the link command for the android part, `compile('com.rollbar:rollbar-android:1.0.0@aar')` or something like that (this one is from rollbar itself and it is for Android Java app), I know Java and React-Native app are not the same thing but it's still Android and Java part anyway so, it's still missing a "compile" component in the `app/build.gradle` file.
However, I tried to add a compile component in this file, but I still have an issue with the `import com.rollbar.RollbarReactNative;`

Thanks

**Comment by rivkahstandig3636** [comment]
Thanks for the report @novose! We'll take a look.

**Comment by rokob** [comment]
You mean this: https://github.com/rollbar/rollbar-react-native/blob/30e6372340a73ff7a46cc00d9046048a52b56f8c/android/build.gradle#L15,L19

**Comment by novose** [comment]
Yes but it's inside rollbar-react-native and it's for java, for the rollbar java component. But maybe it's working like that ok.
However the issue is still here, the import is not working.

**Comment by rokob** [comment]
Creating a fresh react native app via `react-native init MyApp` and following the instructions in the readme, I can build and run an Android app and report items to Rollbar. I am not seeing any import errors. The `react-native link rollbar-react-native` should handle the gradle setup to get the library visible.

**Comment by novose** [comment]
Ok,

Maybe but that won't fix the issue...
And as you already read, I used the "react-native link rollbar-react-native" so that's the point, there is missing something because it's still not working...

**Comment by vijay8233** [comment]
MainApplication.java:35: error: cannot find symbol
            RollbarReactNative.getPackage(),
            ^
  symbol: variable RollbarReactNative

i got this error

**Comment by ginkgomp** [comment]
with `react-native link rollbar-react-native` i got this error...

Error: Expected "\*\/" or [^\*\] but "\*\" found.

**Comment by waltjones** [comment]
Hi @ginkgomp , what version of react-native, and what version of @react-native-community/cli?

If there is an error, it's likely version dependent. Also, React 0.60 should no longer require using react-native link.

**Comment by brianr** [comment]
Closing out old issue.
