### ISSUE TITLE
Expose all Rollbar Methods via NativeModule

### ISSUE THREAD

**Issue by driley-emoney** [rollbar/rollbar-react-native#70]
Currently on the JS side, we have to create a client object using the token. However if we already initialized rollbar on the native side (in AppDelegate) it seems like duplicated code. This means we have to pass our token down through native to JS as well. 

We'd like to be able to initialize rollbar on the native side then simply call:
```
Rollbar.log();
```
On the js side. In native code everything is a singleton anyway, so why not?

**Comment by rokob** [comment]
The short answer is that currently, things that happen in JS stay in JS, they don't delegate to a native client. You are right that there is some duplication that could be cleaned up. It is possible to do what you are saying with some rearchitecting.

**Comment by driley-emoney** [comment]
I see.

One convenience would be for the JS library to be able to instantiate a Client without an access token, and pull the access token from the native side if one already exists. The token could be made available via native module constants so you don't have to worry about async stuff.

Just an idea.

Also, why does everything stay on the JS side? Is the purpose just to reuse the main Rollbar library or do you get some extra crash details this way?

**Comment by waltjones** [comment]
With the popularity of JS-only React Native apps, it's unlikely this SDK will be revised to require the native build in order for the JS side to work.
