### ISSUE TITLE
we should handle offline better in react-native

### ISSUE THREAD

**Issue by letaniaferreira** [rollbar/rollbar-react-native#73]
Support queue up any caught errors and send them once the user reconnects

Maybe something similar to what we do in JavaScript: https://github.com/rollbar/rollbar.js/blob/1e2c7cb1e91353dd90f5bb629a104aa23bb28d2f/src/queue.js#L168

https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/849049/conversations/21756252268

**Comment by brianr** [comment]
Closing out old issue.
