### ISSUE TITLE
Is it possible to use source map without minified url?

### ISSUE THREAD

**Issue by yosimasu** [rollbar/rollbar-react-native#75]
Hi,

I am using the code push service to patch the react native bundle of my clients.
When clients have updated from code push, there would be many different minified urls.
I can not upload source maps for all minified urls.
Is it possible to refer source map by version only?

![螢幕快照 2019-07-05 11 40 26](https://user-images.githubusercontent.com/716511/60697000-b23fc300-9f1a-11e9-9771-f403fcf0667d.png)

**Comment by kousun12** [comment]
I'm also curious as to how we can get sourcemaps to work with code-push. bugsnag seems to have solved this by allowing a glob / wildcard minified url, and i assume they just match on that and un minify in that case. the rollbar docs say

```
minified_url

The URL or filename of the minified file. Can start with http: or https:, which we'll strip off.
```

which made me want to believe that `filename` meant that you'd do a similar matching if the full url didn't match. can i get some clarification on this, or thoughts / pointers on codepush support in general?

**Comment by waltjones** [comment]
Code Push URLs are supported in v0.6.1. PR: https://github.com/rollbar/rollbar-react-native/pull/82

Related Rollbar.js PR: https://github.com/rollbar/rollbar.js/pull/780

URLs will be sent in the form:
iOS: `http://reactnativehost/main.jsbundle`
Android: `http://reactnativehost/index.android.bundle`

If you still have any problems with it, please reopen with details.
