### ISSUE TITLE
Updating configuration with logLevel sets endpoint instead

### ISSUE THREAD

**Issue by driley-emoney** [rollbar/rollbar-react-native#80]
This line is clear bug

https://github.com/rollbar/rollbar-react-native/blob/a25c886fe43f1f167cda84e2bf6fce2df73cda95/ios/RollbarReactNative.m#L205

When you set a logLevel it actually takes its value from endpoint. Pretty egregious

**Comment by waltjones** [comment]
@driley-emoney Thank you for the report. Fixed in 0.6.1.
