### ISSUE TITLE
rollbar-react-native 0.6.0 - 'Rollbar.h' file not found 

### ISSUE THREAD

**Issue by bgneu** [rollbar/rollbar-react-native#86]
I attempted to update our rollbar-react-native dependency to your latest release, 0.6.0, however I keep getting this error when building/archiving my project. 

```
Lexical or Preprocessor Issue Group
/RollbarReactNative.h:6:9: 'Rollbar.h' file not found
/Users/project/path/node_modules/rollbar-react-native/ios/RollbarReactNative.m:1:9: In file included from /Users/project/path/node_modules/rollbar-react-native/ios/RollbarReactNative.m:1:
```

I attempted to uninstall and reinstall the dependency with no luck.

It seems the `rollbar-ios` folder is not getting properly downloaded in the new version because it doesn't show up for me at all, whereas it did on 0.5.0.

Is there something I am missing?

Current config:
React-Native: 0.59.9
Cocoapods: No

**Comment by waltjones** [comment]
@bgneu Thank you for the report. v0.6.1 (just released) should solve the issue.

**Comment by bgneu** [comment]
@waltjones Tried it out, and everything is well with the world. Thanks for the quick response!
