### ISSUE TITLE
Installation instructions for 0.6.1 and react-native 0.60.3

### ISSUE THREAD

**Issue by augustosamame** [rollbar/rollbar-react-native#87]
I have tried to follow the installation instructions here https://rollbar.com/starsona/Starsona-ReactNative/
but it references react-native link which is not used for RN 0.60+
There is no podspec in 0.6.1 node_modules folder

Instructions indicate copying downloaded Rollbar.framework folder into RollbarReactNative.xcodeproj, but there is no such folder.

Can you post updated install instructions for 0.6.1 / RN 0.60.3 ? Thanks!

**Comment by TiagoGouvea** [comment]
I agree. I'm facing the following error when I try to install it on the iOS project.

```
[!] CocoaPods could not find compatible versions for pod "Rollbar":
  In Podfile:
    RollbarReactNative (from `../node_modules/rollbar-react-native`) was resolved to 0.6.1, which depends on
      Rollbar (~> 1.5.0)

None of your spec sources contain a spec satisfying the dependency: `Rollbar (~> 1.5.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

I try to add ` pod "Rollbar", "~> 1.5.0"` on Podfile but the message keep the same.

**Comment by augustosamame** [comment]
There is no podspec in latest rollbar installed node module so the
cocoapods method will not work. This means manual installation but no up to
date instructions anywhere

**Comment by waltjones** [comment]
Looking into this.

**Comment by waltjones** [comment]
@augustosamame @TiagoGouvea Yes, the doc should be updated for RN 0.60+ to skip the link step.

The doc seems to already be correct regarding the Rollbar.framework folder. It specifies this step only for versions < 0.3.0, but perhaps it could be worded more clearly.

About the cocoapods install, I'm not seeing the same thing. Here are my steps:
```
npm install rollbar-react-native --save
cd ios; pod install; cd ..
```
`pod install` output:
```
Installing DoubleConversion (1.1.6)
Installing Folly (2018.10.22.00)
Installing React (0.60.5)
Installing React-Core (0.60.5)
Installing React-DevSupport (0.60.5)
Installing React-RCTActionSheet (0.60.5)
Installing React-RCTAnimation (0.60.5)
Installing React-RCTBlob (0.60.5)
Installing React-RCTImage (0.60.5)
Installing React-RCTLinking (0.60.5)
Installing React-RCTNetwork (0.60.5)
Installing React-RCTSettings (0.60.5)
Installing React-RCTText (0.60.5)
Installing React-RCTVibration (0.60.5)
Installing React-RCTWebSocket (0.60.5)
Installing React-cxxreact (0.60.5)
Installing React-jsi (0.60.5)
Installing React-jsiexecutor (0.60.5)
Installing React-jsinspector (0.60.5)
Installing Rollbar (1.5.2)
Installing RollbarReactNative (0.6.1)
Installing boost-for-react-native (1.63.0)
Installing glog (0.3.5)
Installing yoga (0.60.5.React)
```

Also, the output of `pod search rollbar` looks fine, with both 1.5.0 and 1.5.2 present:
```
-> Rollbar (1.8.1)
   Objective-C library for crash reporting and logging with Rollbar.
   pod 'Rollbar', '~> 1.8.1'
   - Homepage: https://rollbar.com
   - Source:   https://github.com/rollbar/rollbar-ios.git
   - Versions: 1.8.1, 1.8.0-alpha8, 1.8.0-alpha6, 1.8.0-alpha5, 1.8.0-alpha3, 1.7.0, 1.6.0, 1.5.2, 1.5.0, 1.4.2,
   1.4.1, 1.4.0, 1.3.0, 1.2.0, 1.1.0, 1.0.0, 1.0.0-alpha11, 0.2.0, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2 [trunk repo]
```

I am not seeing any issue with pods not installing or with missing podspecs, so I'd like to learn more about what we're doing differently.

**Comment by augustosamame** [comment]
Ok. So I tried it in a brand new project and it works. Delete my
node_modules folder and started from scratch and it worked. The only issue
I had is that it still did not add the podspec reference to Podfile, but
after manually adding '  pod 'RollbarReactNative', :path =>
'../node_modules/rollbar-react-native' ' to Podfile it installed fine.

Thanks for your help.

**Comment by waltjones** [comment]
@augustosamame Great to hear it's working!
