### ISSUE TITLE
How do you reference the client in other place in the app?

### ISSUE THREAD

**Issue by cdesch** [rollbar/rollbar-react-native#9]
As per the instructions, putting this:
```

import { Client } from 'rollbar-react-native'
const rollbar = new Client('token');
```

in 1index.ios.js` and `index.android.js`

How do I now reference the `rollbar` constant in other actions and components in the app?

Do I have to start a `const rollbar = new Client('token');` every time?

**Comment by rokob** [comment]
The same way you would share any instance of an object in your code, you would need to pass a reference to it around. You can do this via something akin to dependency injection by creating the client in one place and passing it down to your other objects. You could also use a singleton by creating your own module that creates one instance and then require that from wherever you need it. The instructions about putting the client into index.ios.js and index.android.js are examples not requirements.

**Comment by cdesch** [comment]
Thanks. I didn't seem apparent at the time.
